---
kind: pipeline
name: test-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: speedcheck
    tags: latest
    dry_run: true

---
kind: pipeline
name: test-arm

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker:linux-arm
  settings:
    repo: speedcheck
    tags: latest
    dry_run: true

---
kind: pipeline
name: test-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker:linux-arm64
  settings:
    repo: speedcheck
    tags: latest
    dry_run: true
